export const ADD_BOOKMARK_ITEM = 'ADD_BOOKMARK_ITEM'
export const REMOVE_BOOKMARK_ITEM = 'REMOVE_BOOKMARK_ITEM'
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
